Add edt to group 1 and group 2
luc65r/db pull request #1
Opened 2021-04-01 09:20 UTC by alyrow

Quick fix to add edt fetch for group 1 & 2, by using comand: `:edt 1 ...` or `edt 2 ...`

Note: You need to add in your `secrets.json`:

```json
"celcat": {
   ...
   "group1": "id of a member of group 1",
   "group2": "id of a member of group 2"
}
```

2021-04-03 19:02 UTC, luc65r requested changes

2021-04-03 19:02 UTC, luc65r commented on cybot/__main__.py
> +    async def edt(self, ctx: commands.Context, group=1, date: Optional[str] = None) -> None:
Il manque le type pour `group`.

2021-04-03 19:02 UTC, luc65r commented on cybot/__main__.py
> +            g = "group2"
C'est pas ici qu'il faut faire ça.

2021-04-03 19:02 UTC, luc65r commented on cybot/__main__.py
> +            c.fetch(g)
Passe seulement `group`.

2021-04-03 19:02 UTC, luc65r commented on cybot/__main__.py
> +            c.fetch(g)
Passe seulement `group`.

2021-04-03 19:02 UTC, luc65r commented on cybot/celcat.py
> +    def fetch(self, group) -> None:
Il manque le type pour `group` (`int`).

2021-04-03 19:02 UTC, luc65r commented on cybot/celcat.py
> +        fid = cfg['celcat'][group]
Remplace `group` par `f'group{group}'` par exemple.
Par contre je suis pas sûr pour les noms dans le fichier de conf.

2021-04-04 13:52 UTC, luc65r requested changes

2021-04-04 13:52 UTC, luc65r commented on cybot/__main__.py
> +#!/usr/bin/python3
Pourquoi ?

2021-04-04 13:52 UTC, luc65r commented on cybot/__main__.py
> +        logging.info(f'{ctx.author} asked for edt')
Évite de changer le style, remets des `"` au lieu de `'`.

2021-04-04 13:52 UTC, luc65r commented on cybot/__main__.py
> +            await ctx.send(f'```\n{c.next_course()}\n```')
Pareil ici.

2021-04-04 13:52 UTC, luc65r commented on cybot/celcat.py
> -
Pourquoi enlever ce saut de ligne ?

2021-04-04 13:52 UTC, luc65r commented on cybot/celcat.py
> +        fid = cfg['celcat'][f'group{group}']
Mets des `"` pour garder le même style.

2021-04-05 08:31 UTC, alyrow commented on cybot/__main__.py
> +#!/usr/bin/python3
J'ai oublié de le retirer après des tests.

2021-04-12 16:28 UTC, merged